# Generated by Django 2.1.5 on 2019-03-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='creater',
            new_name='creator',
        ),
    ]
