# Generated by Django 2.1.5 on 2019-03-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0005_auto_20190327_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignedTo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='createdBy',
        ),
    ]
