# Generated by Django 2.1.5 on 2019-03-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0007_auto_20190331_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-createdAt']},
        ),
    ]
